# Generated by Django 6.0.1 on 2026-03-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='My Shop', max_length=200)),
                ('api_key', models.CharField(help_text='Copy this key into the Flutter desktop app to enable sync.', max_length=128)),
                ('allow_backorders', models.BooleanField(default=False)),
                ('shop_template', models.CharField(default='default', help_text='Template theme folder name under templates/themes/', max_length=64)),
            ],
            options={
                'verbose_name': 'Shop Configuration',
                'verbose_name_plural': 'Shop Configuration',
            },
        ),
    ]
