# Generated by Django 6.0.1 on 2026-03-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfig',
            name='shop_template',
            field=models.CharField(choices=[('default', 'Default Theme'), ('modern', 'Modern Theme')], default='default', help_text='Select the visual theme for the storefront.', max_length=64),
        ),
    ]
