# Generated by Django 5.2.13 on 2026-04-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shopconfig_require_delivery_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col2_heading',
            field=models.CharField(default='Shop', help_text='Heading for footer column 2.', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col2_links',
            field=models.TextField(default='All Products|/\nMy Cart|/cart/', help_text='One link per line in the format: Label|URL'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col3_heading',
            field=models.CharField(default='Company', help_text='Heading for footer column 3.', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col3_links',
            field=models.TextField(default='About Us|#\nSustainability|#\nCareers|#', help_text='One link per line in the format: Label|URL'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col4_heading',
            field=models.CharField(default='Support', help_text='Heading for footer column 4.', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col4_links',
            field=models.TextField(default='Help Center|#\nPrivacy Policy|#\nTerms of Use|#', help_text='One link per line in the format: Label|URL'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_tagline',
            field=models.TextField(default='Quality products delivered to your doorstep. Experience the best of online shopping with us.', help_text='Short description shown below the logo in the footer.'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='hero_button_label',
            field=models.CharField(default='Shop Now', help_text='Label for the primary call-to-action button in the hero.', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='hero_highlight',
            field=models.CharField(default='premium selections', help_text='Second (coloured) line of the hero heading.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero background image (right side on desktop). Leave blank to use the default.', null=True, upload_to='storefront/'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='hero_subtext',
            field=models.TextField(default='Discover our collection featuring elegant designs, sustainable materials, and unmatched quality for your everyday needs.', help_text='Paragraph text shown below the hero heading.'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='hero_tagline',
            field=models.CharField(default='Elevate your lifestyle with', help_text='First line of the large heading in the hero section.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='logo_text',
            field=models.CharField(blank=True, help_text='Text displayed as the logo in the nav bar. Leave blank to use the shop name.', max_length=100),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='nav_link_1_label',
            field=models.CharField(blank=True, help_text='Label for nav link 1 (leave blank to hide).', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='nav_link_1_url',
            field=models.CharField(blank=True, default='/', help_text='URL for nav link 1.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='nav_link_2_label',
            field=models.CharField(blank=True, help_text='Label for nav link 2 (leave blank to hide).', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='nav_link_2_url',
            field=models.CharField(blank=True, default='/', help_text='URL for nav link 2.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='nav_link_3_label',
            field=models.CharField(blank=True, help_text='Label for nav link 3 (leave blank to hide).', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='nav_link_3_url',
            field=models.CharField(blank=True, default='/', help_text='URL for nav link 3.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='nav_link_4_label',
            field=models.CharField(blank=True, help_text='Label for nav link 4 (leave blank to hide).', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='nav_link_4_url',
            field=models.CharField(blank=True, default='/', help_text='URL for nav link 4.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='newsletter_body',
            field=models.TextField(default='Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals.', help_text='Body text inside the newsletter box.'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='newsletter_title',
            field=models.CharField(default='Join our Newsletter', help_text='Heading for the newsletter subscription box.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='promo_badge',
            field=models.CharField(default='Limited Time Offer', help_text='Small uppercase badge label above the promo heading.', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='promo_body',
            field=models.TextField(default='Upgrade your lifestyle with our exclusive collection. Use code LUXE30 at checkout.', help_text='Body text inside the promo banner.'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='promo_button_label',
            field=models.CharField(default='Claim Discount', help_text='CTA button label inside the promo banner.', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='promo_image',
            field=models.ImageField(blank=True, help_text='Right-side image for the promo banner. Leave blank for the default.', null=True, upload_to='storefront/'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='promo_title',
            field=models.CharField(default='Premium Collection is 30% Off', help_text='Main heading inside the promo banner.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='show_benefits',
            field=models.BooleanField(default=True, help_text='Show the Free Shipping / Easy Returns / Secure Payment / 24/7 Support grid.'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='show_newsletter',
            field=models.BooleanField(default=True, help_text='Show the newsletter sign-up box on the homepage.'),
        ),
    ]
