# Generated by Django 5.2.13 on 2026-04-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shopconfig_footer_col2_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='hero_secondary_button_label',
            field=models.CharField(blank=True, default='View Collection', help_text='Label for the secondary (light) CTA button in the hero. Leave blank to hide it.', max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='hero_secondary_button_url',
            field=models.CharField(blank=True, default='#product-grid', help_text='URL for the secondary hero button.', max_length=200),
        ),
    ]
