# Generated by Django 5.2.13 on 2026-04-24 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shopconfig_hero_secondary_button_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Elevate your lifestyle with', max_length=200)),
                ('highlight', models.CharField(default='premium selections', max_length=200)),
                ('subtext', models.TextField(default='Discover our collection featuring elegant designs and unmatched quality.')),
                ('button_label', models.CharField(default='Shop Now', max_length=80)),
                ('button_url', models.CharField(default='#product-grid', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storefront/hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('shop_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='core.shopconfig')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
