# Generated by Django 5.2.13 on 2026-04-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_1_icon',
            field=models.CharField(default='fas fa-truck', help_text='FontAwesome icon class.', max_length=50),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_1_subtext',
            field=models.CharField(default='On all orders over ₹1,000.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_1_title',
            field=models.CharField(default='Free Shipping', max_length=100),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_2_icon',
            field=models.CharField(default='fas fa-undo', max_length=50),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_2_subtext',
            field=models.CharField(default='30 days free return policy.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_2_title',
            field=models.CharField(default='Easy Returns', max_length=100),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_3_icon',
            field=models.CharField(default='fas fa-shield-alt', max_length=50),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_3_subtext',
            field=models.CharField(default='Protected by top-notch security.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_3_title',
            field=models.CharField(default='Secure Payment', max_length=100),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_4_icon',
            field=models.CharField(default='fas fa-headset', max_length=50),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_4_subtext',
            field=models.CharField(default='Our team is always here for you.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='benefit_4_title',
            field=models.CharField(default='24/7 Support', max_length=100),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='support_email',
            field=models.EmailField(default='support@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='support_phone',
            field=models.CharField(default='+91 99999 99999', max_length=20),
        ),
    ]
