# Generated by Django 5.2.13 on 2026-04-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shopconfig_benefit_1_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopconfig',
            name='hero_button_label',
        ),
        migrations.RemoveField(
            model_name='shopconfig',
            name='hero_highlight',
        ),
        migrations.RemoveField(
            model_name='shopconfig',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='shopconfig',
            name='hero_secondary_button_label',
        ),
        migrations.RemoveField(
            model_name='shopconfig',
            name='hero_secondary_button_url',
        ),
        migrations.RemoveField(
            model_name='shopconfig',
            name='hero_subtext',
        ),
        migrations.RemoveField(
            model_name='shopconfig',
            name='hero_tagline',
        ),
    ]
