# Generated by Django 5.2.13 on 2026-04-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_shopconfig_hero_button_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopconfig',
            name='footer_col2_links',
        ),
        migrations.RemoveField(
            model_name='shopconfig',
            name='footer_col3_links',
        ),
        migrations.RemoveField(
            model_name='shopconfig',
            name='footer_col4_links',
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col2_link_1_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col2_link_1_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col2_link_2_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col2_link_2_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col2_link_3_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col2_link_3_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col2_link_4_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col2_link_4_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col3_link_1_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col3_link_1_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col3_link_2_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col3_link_2_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col3_link_3_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col3_link_3_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col3_link_4_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col3_link_4_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col4_link_1_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col4_link_1_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col4_link_2_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col4_link_2_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col4_link_3_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col4_link_3_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col4_link_4_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='footer_col4_link_4_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
    ]
