# Generated by Django 5.2.13 on 2026-04-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_shopconfig_footer_col2_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='subtext',
            field=models.CharField(default='Discover our collection featuring elegant designs and unmatched quality.', max_length=500),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='footer_tagline',
            field=models.CharField(default='Quality products delivered to your doorstep. Experience the best of online shopping with us.', help_text='Short description shown below the logo in the footer.', max_length=500),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='newsletter_body',
            field=models.CharField(default='Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals.', help_text='Body text inside the newsletter box.', max_length=500),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='promo_body',
            field=models.CharField(default='Upgrade your lifestyle with our exclusive collection. Use code LUXE30 at checkout.', help_text='Body text inside the promo banner.', max_length=500),
        ),
    ]
