# Generated by Django 5.2.13 on 2026-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_heroslide_subtext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='show_sidebar_promo',
            field=models.BooleanField(default=True, help_text='Show the promotional box in the product list sidebar.'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='sidebar_promo_body',
            field=models.CharField(default='On all orders above ₹1,000.', help_text='Subtext for the sidebar promo box.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='sidebar_promo_icon',
            field=models.CharField(default='fas fa-shipping-fast', help_text='FontAwesome icon class.', max_length=50),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='sidebar_promo_title',
            field=models.CharField(default='Free Delivery', help_text='Heading for the sidebar promo box.', max_length=100),
        ),
    ]
