# Generated by Django 5.2.13 on 2026-04-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shopconfig_show_sidebar_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='show_top_bar',
            field=models.BooleanField(default=True, help_text='Show a thin informational bar above the main navigation.'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='store_address',
            field=models.CharField(default='123 Luxury Street, Fashion District', help_text='Physical address shown in the top bar.', max_length=500),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='top_bar_offer',
            field=models.CharField(default='Free Shipping on all orders over ₹1,000!', help_text='Special announcement or offer text for the top bar.', max_length=200),
        ),
    ]
