# Generated by Django 5.2.13 on 2026-04-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_shopconfig_show_top_bar_shopconfig_store_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfig',
            name='shop_template',
            field=models.CharField(choices=[('default', 'Default Theme'), ('modern', 'Modern Theme'), ('aurora', 'Aurora Theme')], default='default', help_text='Select the visual theme for the storefront.', max_length=64),
        ),
    ]
