# Generated by Django 5.2.13 on 2026-04-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_shopconfig_shop_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='highlight',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtext',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
