# Generated by Django 5.2.13 on 2026-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_heroslide_button_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a logo image. If provided, this will be used instead of logo text.', null=True, upload_to='shop/'),
        ),
    ]
