# Generated by Django 5.2.13 on 2026-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_shopconfig_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='promo_button_url',
            field=models.CharField(default='/', help_text='URL for the promo banner button.', max_length=200),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='show_promo_banner',
            field=models.BooleanField(default=True, help_text='Show or hide the promotional banner section on the homepage.'),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='shop_template',
            field=models.CharField(choices=[('default', 'Default Theme'), ('aurora', 'Aurora Theme'), ('squareshoppe', 'SquareShoppe Theme')], default='default', help_text='Select the visual theme for the storefront.', max_length=64),
        ),
    ]
