# Generated by Django 5.2.13 on 2026-04-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_b64',
            field=models.TextField(blank=True, default='', help_text='Raw base64-encoded WebP image (no data: prefix). Synced from the desktop app.'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_b64',
            field=models.TextField(blank=True, default='', help_text='Raw base64-encoded WebP image (no data: prefix). Synced from the desktop app.'),
        ),
    ]
