# Generated by Django 6.0.1 on 2026-03-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delivery_slots'),
        ('orders', '0003_retailtransaction'),
    ]

    operations = [
    ]
