# Generated by Django 5.2.13 on 2026-04-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_onlineorder_delivery_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
